### ISSUE TITLE
Add 2 sticker Path for Sticker in Doki Theme Extension Setting

### ISSUE THREAD

**Issue by am0029** [cyclic-reference/doki-theme-vscode#184]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Unthrottled** [comment]
I'm not sure I am following what you are asking for. Do you want 2 stickers?

If that's the case just make a custom image with both of the images. Unless I am misunderstanding.

**Comment by am0029** [comment]
Thanks   in doki theme setting you can just add exact path of 1 sticker with css bottom right fixed

If possible in setting add 2 or 3 or more options for more custom image  sticker path . i want add 5 custom  sticker to my vs code 1 top right top left bottom right bottom left .  but in doki theme setting it just 1 line for adding your sticker path  

u mean i pay for some one do Photoshop a picture for me ? transparent picture with 4 sticker ? 

it does not make sense but ok

thanks for answering 

god bless you

**Comment by am0029** [comment]
see this picture it just 1 line for sticker path . i want add 4 sticker path how can i do that ?

[https://ibb.co/RQnMkxG](url)
